platform:
  - x64

image:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: 10

clone_folder: c:\projects\npm-opencv-build

install:
  - cmd: choco install cmake -y
  - cmd: choco upgrade cmake
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - SET PATH=%PATH%;C:\Program Files\CMake\bin;

build_script:
  - cd c:\projects\npm-opencv-build
  - SET OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION=4.1.1
  - npm install

test_script:
  - npm test
  - cd c:\projects
  - git clone https://github.com/nut-tree/opencv4nodejs
  - cd opencv4nodejs
  - set OPENCV4NODEJS_PREBUILT_SKIP_DEPENDENCIES=1
  # install new opencv-build version
  - npm install ../npm-opencv-build
  - npm install
  - cd test
  - npm install
  - npm run test-appveyor
  - set "OPENCV4NODEJS_PREBUILT_SKIP_DEPENDENCIES="

on_success:
  - cmd: cd c:\projects\npm-opencv-build
  - tar -czf opencv-build.tar -h -C .. -T package_win32.txt
  - IF defined APPVEYOR_REPO_TAG_NAME npm publish opencv-build.tar
